language: node_js

node_js:
  - "7"
  - "8"

install:
  - npm install
  - npm install quasar-cli

script:
  - quasar build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "dist"
  repo: "larry-quasar-ui-deploy"
  fqdn: "larry.asw.io"
