language: node_js

node_js:
  - "8"

notifications:
  email: false
  irc: "irc.euirc.net#openclonk-dev"

install:
  - npm install

script:
  - npm run-script build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "dist"
  repo: "asmaps/larry-quasar-ui-deploy"
  fqdn: "larry.asw.io"
